Backport of env2yaml arm64 Docker build context fixes
This commit contains fixes made to the main 8.x branch to generate
arm64 and amd64 env2yaml binaries, copy them into the build context
and correctly identify the correct binary in the Dockerfile to
include in the Docker image.

A clean backport was not available due to the change in format of
Dockerfile template from j2 to erb in #15142

This contains fixes from #15980 and #16053.

diff --git a/docker/templates/Dockerfile.j2 b/docker/templates/Dockerfile.j2
--- a/docker/templates/Dockerfile.j2
+++ b/docker/templates/Dockerfile.j2
@@ -147,7 +147,25 @@ ADD pipeline/default.conf pipeline/logstash.conf
 RUN chown --recursive logstash:root config/ pipeline/
 # Ensure Logstash gets the correct locale by default.
 ENV LANG={{ locale }} LC_ALL={{ locale }}
-ADD env2yaml/env2yaml /usr/local/bin/
+
+# Copy over the appropriate env2yaml artifact
+COPY env2yaml/env2yaml-amd64 env2yaml/
+COPY env2yaml/env2yaml-arm64 env2yaml/
+
+RUN env2yamlarch="$(arch)"; \
+  case "${env2yamlarch}" in \
+    'x86_64') \
+      env2yamlarch=amd64; \
+      ;; \
+    'aarch64') \
+      env2yamlarch=arm64; \
+      ;; \
+    *) echo >&2 "error: unsupported architecture '$env2yamlarch'"; exit 1 ;; \
+  esac; \
+  cp env2yaml/env2yaml-${env2yamlarch} /usr/local/bin/env2yaml; \
+  rm -rf env2yaml
+
+
 # Place the startup wrapper script.
 ADD bin/docker-entrypoint /usr/local/bin/
 {% else -%}
@@ -156,6 +174,7 @@ COPY scripts/config/logstash.yml config/logstash.yml
 COPY scripts/config/log4j2.properties config/
 COPY scripts/pipeline/default.conf pipeline/logstash.conf
 RUN chown --recursive logstash:root config/ pipeline/
+
 # Place the startup wrapper script.
 COPY scripts/bin/docker-entrypoint /usr/local/bin/
 {% endif -%}
