Update Dockerfile.erb

diff --git a/docker/templates/Dockerfile.erb b/docker/templates/Dockerfile.erb
--- a/docker/templates/Dockerfile.erb
+++ b/docker/templates/Dockerfile.erb
@@ -68,34 +68,34 @@ FROM <%= base_image %>
 
 RUN for iter in {1..10}; do \
 <% if image_flavor == 'full' || image_flavor == 'oss' -%>
-export DEBIAN_FRONTEND=noninteractive && \
+    export DEBIAN_FRONTEND=noninteractive && \
 <% end -%>
-<%= package_manager %> update -y && \
+    <%= package_manager %> update -y && \
 <% if image_flavor != 'ironbank' -%>
-<%= package_manager %> upgrade -y && \
+    <%= package_manager %> upgrade -y && \
 <% end -%>
-<%= package_manager %> install -y procps findutils tar gzip curl && \
+    <%= package_manager %> install -y procps findutils tar gzip curl && \
 <% if image_flavor == 'ubi8' -%>
-<%= package_manager %> install -y openssl && \
+    <%= package_manager %> install -y openssl && \
 <% end -%>
 <% if image_flavor == 'ubi8' || image_flavor == 'ironbank' -%>
-<%= package_manager %> install -y which shadow-utils && \
+    <%= package_manager %> install -y which shadow-utils && \
 <% else -%>
-<%= package_manager %> install -y locales && \
+    <%= package_manager %> install -y locales && \
 <% end -%>
-<%= package_manager %> clean all && \
+    <%= package_manager %> clean all && \
 <% if image_flavor == 'full' || image_flavor == 'oss' -%>
-locale-gen 'en_US.UTF-8' && \
-<%= package_manager %> clean metadata && \
+    locale-gen 'en_US.UTF-8' && \
+    <%= package_manager %> clean metadata && \
 <% end -%>
-exit_code=0 && break || exit_code=$? && \
-echo "packaging error: retry $iter in 10s" && \
-<%= package_manager %> clean all && \
+    exit_code=0 && break || exit_code=$? && \
+    echo "packaging error: retry $iter in 10s" && \
+    <%= package_manager %> clean all && \
 <% if image_flavor == 'full' || image_flavor == 'oss' -%>
-<%= package_manager %> clean metadata && \
+    <%= package_manager %> clean metadata && \
 <% end -%>
-sleep 10; done; \
-(exit $exit_code)
+    sleep 10; done; \
+    (exit $exit_code)
 
 # Provide a non-root user to run the process.
 RUN groupadd --gid 1000 logstash && \
