Validate supplied branch and tag exist for RN gen
Add a validation step to the action for generating release notes. Without input
validation tags/branches that do not exist (due to typo, errors in workflow
inputs) can go un-noticed with PRs that have empty commit ranges.

diff --git a/.github/workflows/gen_release_notes.yml b/.github/workflows/gen_release_notes.yml
--- a/.github/workflows/gen_release_notes.yml
+++ b/.github/workflows/gen_release_notes.yml
@@ -25,6 +25,19 @@ jobs:
     - uses: actions/checkout@v6
       with:
         fetch-depth: 0
+    - name: Validate the supplied target branch and last release tag exist
+      run: |
+        git fetch --tags
+        
+        if ! git rev-parse --verify "origin/${{ github.event.inputs.branch }}" >/dev/null 2>&1; then
+          echo "Error: Branch ${{ github.event.inputs.branch }} does not exist"
+          exit 1
+        fi
+        
+        if ! git rev-parse --verify "v${{ github.event.inputs.last_release }}" >/dev/null 2>&1; then
+          echo "Error: Tag v${{ github.event.inputs.last_release }} does not exist"
+          exit 1
+        fi
     - name: Set up Ruby
       uses: ruby/setup-ruby@v1
       with:
